<div class="col-md-8">
        <form name="addData" method="post" id="addData" class="form"
        action="<?php echo $block->getBaseUrl().'empmodule/index/save'; ?>"
              data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <legend class="legend"><span><?= $block->escapeHtmlAttr(__('Enter Credentials:')) ?></span></legend>
                <legend class="legend"><span><?= $block->escapeHtmlAttr(__('Enter correct details for Secure Data storage ')) ?></span></legend>
                <fieldset class="fieldset row">
                    <div class="fields col-md-6">
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                escapeHtmlAttr(__('Employee ID')) ?></span></label>
                            <div class="control">
                                <input name="empid" id="empid" title="empid" value="" class="input-text" type="text"
                                       data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                escapeHtmlAttr(__('First Name')) ?></span></label>
                            <div class="control">
                                <input name="fname" id="fname" title="fname" value="" class="input-text" type="text"
                                       data-validate="{required:true, 'validate-alpha-with-spaces':true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Last Name')) ?></span></label>
                            <div class="control">
                                <input name="lname" id="lname" title="lname" value="" class="input-text"
                                       type="text" data-validate="{required:true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Email id')) ?></span></label>
                            <div class="control">
                                <input name="email" id="email" title="email" value="" class="input-text"
                                       type="email" data-validate="{required:true, 'validate-email':true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Company Name')) ?></span></label>
                            <div class="control">
                                <input name="cname" id="cname" title="cname" value="" class="input-text"
                                       type="text" data-validate="{required:true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Department')) ?></span></label>
                            <div class="control">
                                <input name="dept" id="dept" title="dept" value="" class="input-text"
                                       type="text" data-validate="{required:true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Occupation')) ?></span></label>
                            <div class="control">
                                <input name="occupation" id="occupation" title="occupation" value="" class="input-text"
                                       type="text" data-validate="{required:true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Mobile Number')) ?></span></label>
                            <div class="control">
                                <input name="mobno" id="mobno" title="mobno" value="" class="input-text"
                                       type="number" data-validate="{required:true}">
                            </div>
                        </div>
                        
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Address')) ?></span></label>
                            <div class="control">
                            <input name="address" id="address" title="address" value="" class="input-text"
                                       type="text" data-validate="{required:true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Joining Date')) ?></span></label>
                            <div class="control">
                                <input name="jdate" id="jdate" title="jdate" value="" class="input-text"
                                       type="date" data-validate="{rquired:true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Date Of Birth')) ?></span></label>
                            <div class="control">
                                <input name="bdate" id="bdate" title="bdate" value="" class="input-text"
                                       type="date" data-validate="{required:true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <!-- <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Remember me')) ?></span></label> -->
                            <div class="control">
                            <label><input id="rememberme" name="rememberme" value="remember" type="checkbox" /> &nbsp;Remember me</label> 
                            </div>
                        </div>
                    </div>
                </fieldset>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary" title="Save"><span><?= $block->
                        escapeHtmlAttr(__('Submit')) ?></span></button>
                </div>
            </div>
        </form>
    </div>
</div>